;******************************************************************************
; *
; Filename: PICInterface.asm *
; Date: March 14, 2025 *
; Author: Andrew Keller *
; Company: Idaho State University *
; Description: Interfaces via UART to receive and execute commands *
; Github: https://github.com/andrew1593571/RCET3375.git *
; *
;******************************************************************************
  
    INCLUDE PICInterfaceSetup.inc
    #include "p16f883.inc"

; CONFIG1
; __config 0xE0FA
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    ORG H'000'
    GOTO SETUP
    
    ORG H'004'
    GOTO INTERRUPT
    
SETUP:
    CALL INITIALIZE	    ;CALLS THE INITIALIZE SUBROUTINE IN INCLUDE FILE
    GOTO MAIN
    
INTERRUPT:
    BTFSC PIR1, RCIF	    ;IF UART RECEIVE INTERRUPT, GOTO UARTRECEIVE ISR
    GOTO UARTRECEIVE
    
    BTFSC PIR1, TMR2IF	    ;IF TIMER2 INTERRUPT, GOTO TMR2ISR
    GOTO TMR2ISR
    
    BTFSC PIR1, ADIF	    ;IF ADC INTERRUPT, GOTO ADCISR
    GOTO ADCISR
    
    RETFIE
    
UARTRECEIVE:
    BCF PIR1, RCIF	    ;CLEAR RCIF INTERRUPT FLAG
    BTFSC COMMAND, 0
    GOTO UPDATESERVO
    BTFSC COMMAND, 1
    GOTO STARTADC
    MOVF RCREG, W	    ;RETRIEVE DATA
    XORLW H'24'		    ;COMPARE THE RECEIVED DATA TO THE $
    BTFSC STATUS, Z	    ;IF THE RECEIVED BYTE IS NOT $, RETFIE
    BSF COMMAND, 0	    ;SETS THE SERVOREC FLAG FOR THE NEXT UART INTERRUPT
    BSF COMMAND, 1	    ;SETS THE ADCREQ FLAG
    RETFIE
    
UPDATESERVO:
    BCF COMMAND, 0
    MOVF RCREG, W	    ;RECEVED BYTE IS $, GET NEXT BYTE
    MOVWF SERVOPOS	    ;MOVE NEXT BYTE INTO SERVOPOS
    RETFIE
    
STARTADC:
    BSF PORTC, RC1
    MOVF RCREG, W
    XORLW H'51'		    ;COMPARE AGAINST ADC COMMAND BYTE
    BTFSC STATUS, Z
    BSF ADCON0, GO	    ;IF RECEIVED BYTE REQUESTS ADC, START CONVERSION
    BCF COMMAND, 1	    ;CLEAR THE ADCREQ FLAG
    RETFIE
    
TMR2ISR:
    BCF PIR1, TMR2IF	    ;CLEAR TMR2IF
    DECFSZ COUNTLSB	    ;IF COUNTLSB IS NOT 0, RETFIE
    RETFIE
    DECFSZ COUNTMSB	    ;IF COUNTMSB IS NOT 0, RETFIE
    RETFIE
    
    BTFSS PORTC, RC0	    ;IF RC0 IS LOW, START THE PULSE WIDTH
    GOTO STARTPW
    
    BCF PORTC, RC0	    ;SET RC0 LOW
    MOVLW H'13'		    ;LOAD MSB OF PULSE SPACE COUNT
    MOVWF COUNTMSB	    
    MOVLW H'88'		    ;LOAD LSB OF PULSE SPACE COUNT
    MOVWF COUNTLSB
    RETFIE
    
STARTPW:
    MOVF SERVOPOS, W	    ;MOVE SERVOPOS INTO W, ADD 250
    ADDLW H'FA'
    MOVWF COUNTLSB	    ;MOVE W INTO COUNT LSB
    BTFSC STATUS, 0	    ;IF OVERFLOW, LOAD 2 INTO MSB
    MOVLW H'02'
    BTFSS STATUS, 0	    ;IF NO OVERFLOW, LOAD 1 INTO MSB
    MOVLW H'01'
    MOVWF COUNTMSB
    BSF PORTC, RC0	    ;SET PORTC
    RETFIE

ADCISR:
    BCF PIR1, ADIF
    MOVF ADRESH, W	    ;MOVE MSB BITS OF ADC RESULT TO UART TRANSMIT
    MOVWF TXREG
    BANKSEL ADRESL	    ;MOVE LSB BITS OF ADC RESULT TO UART TRANSMIT
    MOVF ADRESL, W
    BANKSEL TXREG
    MOVWF TXREG
    RETFIE
    
    
MAIN:
    GOTO MAIN
    END