;******************************************************************************
; *
; Filename: SixInterrupt.asm *
; Date: February 25, 2025 *
; Author: Andrew Keller *
; Company: Idaho State University *
; Description: INPUT DESCRIPTION HERE *
; Github: https://github.com/andrew1593571/RCET3375.git *
; *
;******************************************************************************
  
    INCLUDE PIC16F883SixInterruptSetup.inc
    #include "p16f883.inc"

; CONFIG1
; __config 0xE0F1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    ORG H'000'
    GOTO SETUP
    
    ORG H'004'
    GOTO INTERRUPT
    
SETUP:
    CALL INITIALIZE	    ;CALLS THE INITIALIZE SUBROUTINE IN INCLUDE FILE
    BANKSEL PORTC
    GOTO MAIN
    
INTERRUPT:
    MOVWF STOREW	    ;STORE W INTO GENERAL REGISTER IMMEDIATELY
    MOVF STATUS, 0	    ;MOVE STATUS REGISTER INTO W
    MOVWF STORESTATUS	    ;MOVE W INTO STORESTATUS REGISTER
    
    BTFSC INTCON, RBIF	    ;IF PORTB CALLED INTERRUPT, DISPLAY SEVEN
    GOTO CHECKPORTB 
    
    GOTO RESETINTERRUPTS

CHECKPORTB:
    BCF INTCON, RBIF	    ;CLEAR THE RBIF FLAG
    
    BTFSC PORTB, RB1	    ;IF RB1 IS HIGH, DISPLAY A SIX
    GOTO DISPLAYSIX
    
    GOTO ENDINTERRUPT	    ;IF NONE OF PORTB MEET CRITERIA, END INTERRUPT
    
DISPLAYSIX:
    MOVLW H'36'
    MOVWF PORTC
    
    MOVLW H'5F'		    ;SETUP DELAY FOR SIX
    MOVWF SIXCOUNTA
    MOVLW H'26'
    MOVWF SIXCOUNTB
    MOVLW H'0B'
    MOVWF SIXCOUNTC
SIXDELAY:		    ;DELAY FOR 2 SECONDS
    DECFSZ SIXCOUNTA
    GOTO SIXDELAY
    DECFSZ SIXCOUNTB
    GOTO SIXDELAY
    DECFSZ SIXCOUNTC
    GOTO SIXDELAY
    
    GOTO ENDINTERRUPT

RESETINTERRUPTS:
    MOVLW B'10001000'	    ;CONFIGURE INTERRUPT CONTROL REGISTER
    MOVWF INTCON
ENDINTERRUPT:
    MOVF STORESTATUS, 0	    ;MOVE STORESTATUS INTO W REGISTER
    MOVWF STATUS	    ;MOVE W INTO THE STATUS REGISTER
    MOVF STOREW, 0	    ;RESTORE WHAT WAS IN W REGISTER
    
    RETFIE		    ;RETURN AND RE-ENABLE INTERRUPTS 
    
MAIN:
    MOVLW H'31'
    MOVWF PORTC
    
    GOTO MAIN
    END