;******************************************************************************
; *
; Filename: FileName.asm *
; Date: February 03, 2025 *
; Author: Andrew Keller *
; Company: Idaho State University *
; Description: INPUT DESCRIPTION HERE *
; Github: https://github.com/andrew1593571/RCET3375.git *
; *
;******************************************************************************
  

;***********************************************
;DEFINE GENERAL FUNCTION REGISTERS
;***********************************************

;REGISTERNAME EQU H'0020;    ;COMMENT HERE


;***********************************************
;DEFINE CONSTANTS
;***********************************************

;CONSTANTNAME EQU H'00'    ;COMMENT HERE


;***********************************************
;DEFINE PIN/BIT LABELS
;******************se*****************************

;DEFINE PINS HERE


;***********************************************
;INITIALIZE PIC16F883 AND SETUP
;***********************************************

SETUP_CODE CODE	    ;START OF THE FILE
    
INITIALIZE:
    GOTO INITIALIZE

;----------PORTA CONFIGURATION----------

;----------PORTB CONFIGURATION----------

;----------PORTC CONFIGURATION----------
    
    RETURN