;******************************************************************************
; *
; Filename: KeypadDisplay.asm *
; Date: February 03, 2025 *
; Author: Andrew Keller *
; Company: Idaho State University *
; Description: Displays a number or letter on the LED matrix using 4x4 keypad *
; *
;******************************************************************************
  
#include "p16f883.inc"

; CONFIG1
; __config 0xE0F1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

 
    ORG H'000'
    GOTO SETUP
    
    ORG H'004'
    RETFIE
    
SETUP
    BANKSEL ANSELH  ;DISABLE ANALOG INPUTS ON PORT B
    MOVLW H'00'
    MOVWF ANSELH
    BANKSEL IOCB    ;DISABLE INTERRUPT ON CHANGE FOR PORT B
    MOVLW H'00'
    MOVWF IOCB
    BANKSEL PORTB   ;CLEAR PORT B
    CLRF PORTB	    
    BANKSEL TRISB   ;SET TRISTATE B TO OUTPUT FOR 0-3 AND INPUT FOR 4-7
    MOVLW H'F0'
    MOVWF TRISB
    BANKSEL WPUB    ;DISABLE PORT B PULL-UPS
    MOVLW H'00'
    MOVWF WPUB
    
    BANKSEL PORTC   ;CLEAR PORT C, SET AS OUTPUTS, SET DISPLAY BLANK
    CLRF PORTC
    BANKSEL TRISC   ;SET TRISTATE C TO OUTPUT
    MOVLW H'00'
    MOVWF TRISC
    BANKSEL PORTC   ;WRITE A BLANK TO THE LED MATRIX
    MOVLW H'20'
    MOVWF PORTC
    
    GOTO MAIN
    
    
DIS_ASTERISK
    BANKSEL PORTC   ;WRITE AN ASTERISK TO THE LED MATRIX
    MOVLW H'2A'
    MOVWF PORTC
    GOTO MAIN
    
DIS_POUND
    BANKSEL PORTC   ;WRITE A POUND TO THE LED MATRIX
    MOVLW H'23'
    MOVWF PORTC
    GOTO MAIN
    
DIS_A
    BANKSEL PORTC   ;WRITE A TO THE LED MATRIX
    MOVLW H'41'
    MOVWF PORTC
    GOTO MAIN
    
DIS_B
    BANKSEL PORTC   ;WRITE B TO THE LED MATRIX
    MOVLW H'42'
    MOVWF PORTC
    GOTO MAIN
    
DIS_C
    BANKSEL PORTC   ;WRITE C TO THE LED MATRIX
    MOVLW H'43'
    MOVWF PORTC
    GOTO MAIN
    
DIS_D
    BANKSEL PORTC   ;WRITE D TO THE LED MATRIX
    MOVLW H'44'
    MOVWF PORTC
    GOTO MAIN
    
DIS_0
    BANKSEL PORTC   ;WRITE 0 TO THE LED MATRIX
    MOVLW H'30'
    MOVWF PORTC
    GOTO MAIN
    
DIS_1
    BANKSEL PORTC   ;WRITE 1 TO THE LED MATRIX
    MOVLW H'31'
    MOVWF PORTC
    GOTO MAIN
    
DIS_2
    BANKSEL PORTC   ;WRITE 2 TO THE LED MATRIX
    MOVLW H'32'
    MOVWF PORTC
    GOTO MAIN
    
DIS_3
    BANKSEL PORTC   ;WRITE 3 TO THE LED MATRIX
    MOVLW H'33'
    MOVWF PORTC
    GOTO MAIN
    
DIS_4
    BANKSEL PORTC   ;WRITE 4 TO THE LED MATRIX
    MOVLW H'34'
    MOVWF PORTC
    GOTO MAIN
    
DIS_5
    BANKSEL PORTC   ;WRITE 0 TO THE LED MATRIX
    MOVLW H'35'
    MOVWF PORTC
    GOTO MAIN
    
DIS_6
    BANKSEL PORTC   ;WRITE 6 TO THE LED MATRIX
    MOVLW H'36'
    MOVWF PORTC
    GOTO MAIN
    
DIS_7
    BANKSEL PORTC   ;WRITE 7 TO THE LED MATRIX
    MOVLW H'37'
    MOVWF PORTC
    GOTO MAIN
    
DIS_8
    BANKSEL PORTC   ;WRITE 8 TO THE LED MATRIX
    MOVLW H'38'
    MOVWF PORTC
    GOTO MAIN
    
DIS_9
    BANKSEL PORTC   ;WRITE 9 TO THE LED MATRIX
    MOVLW H'39'
    MOVWF PORTC
    GOTO MAIN
    
MAIN
    
    END