;******************************************************************************
; *
; Filename: EEPROMRecording.asm *
; Date: March 21, 2025 *
; Author: Andrew Keller *
; Company: Idaho State University *
; Description: When the record button is pressed, 10 keypad buttons are
;                recorded and stored in EEPROM for playback when play pressed *
; Github: https://github.com/andrew1593571/RCET3375.git *
; *
;******************************************************************************
  
    INCLUDE EEPROMRecordingSetup.inc
    #include "p16f883.inc"

; CONFIG1
; __config 0xE0F2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    ORG H'000'
    GOTO SETUP
    
    ORG H'004'
    GOTO INTERRUPT
    
SETUP:
    CALL INITIALIZE	    ;CALLS THE INITIALIZE SUBROUTINE IN INCLUDE FILE
    GOTO MAIN

READ_EEPROM:
    RETURN
    
INTERRUPT:
    BTFSC INTCON, RBIF	    ;CHECK FOR A CHANGE ON PORTB
    GOTO IOCISR
    BANKSEL PIR1
    BTFSC PIR1, TMR2IF	    ;CHECK FOR A TIMER INTERRUPT
    GOTO TMR2ISR
    RETFIE
    
IOCISR:
    RETFIE
    
TMR2ISR:
    BCF PIR1, TMR2IF
    DECFSZ TMRCOUNT
    GOTO CHANGEDISPLAY
    RETFIE
    
CHANGEDISPLAY:
    MOVLW TMRCOUNTRESET	    ;LOAD THE TIMER COUNT RESET VALUE INTO W
    MOVWF TMRCOUNT	    ;MOVE W INTO TMRCOUNT
    BTFSC RECMODE, PLAY	    ;IF PLAY FLAG IS HIGH, GOTO PLAYBACK
    GOTO PLAYBACK
    BTFSC RECMODE, RECORD   ;IF RECORD FLAG IS HIGH, GOTO TOGGLE_R
    GOTO TOGGLE_R
    
    MOVF PORTC, W	    ;MOVE PORTC TO W
    BTFSC STATUS, Z	    ;IF W IS ZERO, GOTO CLEARPORTC
    GOTO CLEARPORTC
    MOVLW MTX_S		    ;ELSE DISPLAY S IN DOT MATRIX
    MOVWF PORTC
    RETFIE
    
PLAYBACK:
    MOVF PCOUNT, W	    ;MOVE PCOUNT INTO W
    BTFSS STATUS, Z	    ;IF PCOUNT IS NOT 0, SKIP TO DISPLAYNEXT
    GOTO DISPLAYNEXT
    BANKSEL EEADR
    CLRF EEADR		    ;SET EEPROM ADDRESS TO 0x00
    CALL READ_EEPROM	    ;CALL THE READ_EEPROM SUBROUTINE
    BANKSEL PCOUNT
    MOVWF PCOUNT	    ;MOVE W TO PCOUNT
    BANKSEL EEADR
    INCF EEADR		    ;INCREMENT EEADR
DISPLAYNEXT:
    CALL READ_EEPROM	    ;CALL READ_EEPROM SUBROUTINE
    BANKSEL PORTC
    MOVWF PORTC		    ;MOVE W TO PORTC
    BANKSEL EEADR
    INCF EEADR		    ;INCREMENT EEADR
    BANKSEL PCOUNT
    DECF PCOUNT		    ;DECREAMENT PCOUNT
    RETFIE
    
TOGGLE_R:
    MOVF PORTC, W	    ;MOVE PORTC TO W
    BTFSC STATUS, Z	    ;IF W IS ZERO, GOTO CLEARPORTC
    GOTO CLEARPORTC
    MOVLW MTX_R		    ;ELSE DISPLAY R IN DOT MATRIX
    MOVWF PORTC
    RETFIE
    
CLEARPORTC:
    CLRF PORTC
    RETFIE
    
MAIN:
    
    GOTO MAIN
    END