;******************************************************************************
; *
; Filename: SevenInterrupt.asm *
; Date: February 24, 2025 *
; Author: Andrew Keller *
; Company: Idaho State University *
; Description: Displays a 1, Displays 7 when interrupted *
; Github: https://github.com/andrew1593571/RCET3375.git *
; *
;******************************************************************************
  
    INCLUDE "PIC16F883SevenInterruptSetup.inc"
    #include "p16f883.inc"

; CONFIG1
; __config 0xE0F1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    ORG H'000'
    GOTO SETUP
    
    ORG H'004'
    GOTO INTERRUPT
    
SETUP:
    CALL INITIALIZE	    ;CALLS THE INITIALIZE SUBROUTINE IN INCLUDE FILE
    BANKSEL PORTC

    GOTO MAIN
    
INTERRUPT:
    MOVWF STOREW	    ;STORE W INTO GENERAL REGISTER IMMEDIATELY
    MOVF STATUS, 0	    ;MOVE STATUS REGISTER INTO W
    MOVWF STORESTATUS	    ;MOVE W INTO STORESTATUS REGISTER
    
    BTFSC INTCON, RBIF	    ;IF PORTB CALLED INTERRUPT, DISPLAY SEVEN
    GOTO CHECKPORTB 
    
    GOTO RESETINTERRUPTS

CHECKPORTB:
    BCF INTCON, RBIF	    ;CLEAR THE RBIF FLAG
    
    BTFSC PORTB, RB0	    ;IF RB0 IS HIGH, DISPLAY A SEVEN
    GOTO DISPLAYSEVEN
    
    GOTO ENDINTERRUPT	    ;IF NONE OF PORTB MEET CRITERIA, END INTERRUPT
    
DISPLAYSEVEN:
    MOVLW H'37'
    MOVWF PORTC
    
    MOVLW H'5F'		    ;SETUP DELAY FOR SEVEN
    MOVWF SEVENCOUNTA
    MOVLW H'26'
    MOVWF SEVENCOUNTB
    MOVLW H'0B'
    MOVWF SEVENCOUNTC
SEVENDELAY:		    ;DELAY FOR 2 SECONDS
    DECFSZ SEVENCOUNTA
    GOTO SEVENDELAY
    DECFSZ SEVENCOUNTB
    GOTO SEVENDELAY
    DECFSZ SEVENCOUNTC
    GOTO SEVENDELAY
    
    GOTO ENDINTERRUPT

RESETINTERRUPTS:
    MOVLW B'10001000'	    ;CONFIGURE INTERRUPT CONTROL REGISTER
    MOVWF INTCON
ENDINTERRUPT:
    MOVF STORESTATUS, 0	    ;MOVE STORESTATUS INTO W REGISTER
    MOVWF STATUS	    ;MOVE W INTO THE STATUS REGISTER
    MOVF STOREW, 0	    ;RESTORE WHAT WAS IN W REGISTER
    
    RETFIE		    ;RETURN AND RE-ENABLE INTERRUPTS 
    
MAIN:
    MOVLW H'31'
    MOVWF PORTC
    
    GOTO MAIN
    END